version: '3'
services:
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: udprn
      POSTGRES_DB: udprns
      
  app:
    build: .
    command: npm start
    volumes:
    - .:/usr/src/app
    ports:
    - "8080:8080"
    depends_on: 
    - postgres
    environment:
      DATABASE_URL: postgres://udprn@postgres/udprns
      HOST: "0.0.0.0"
      PORT: "8080"